"""Map verbose Wikidata POS labels to short WN-LMF POS codes."""
from wn.constants import (
    ADP,
    ADV,
    CONJ,
    DET,
    INTERROGATIVE,
    INTJ,
    NUM,
    OTHER,
    PART,
    PRON,
)

POS_MAP: dict[str, str] = {
    "pronoun": PRON,
    "personal pronoun": PRON,
    "possessive determiner": PRON,
    "reflexive personal pronoun": PRON,
    "reflexive pronoun": PRON,
    "reciprocal pronoun": PRON,
    "interrogative pronoun": PRON,
    "indefinite pronoun": PRON,
    "relative pronoun": PRON,
    "demonstrative pronoun": PRON,
    "definite pronoun": PRON,
    "pronominal locution": PRON,
    "determiner": DET,
    "definite article": DET,
    "indefinite article": DET,
    "demonstrative determiner": DET,
    "adverbial phrase": ADV,
    "adverbial locution": ADV,
    "adverbial particle": ADV,
    "interrogative adverb": ADV,
    "prepositional adverb": ADV,
    "preposition": ADP,
    "prepositional locution": ADP,
    "conjunction": CONJ,
    "numeral": NUM,
    "interjection": INTJ,
    "interrogative word": INTERROGATIVE,
    "interrogative expression": INTERROGATIVE,
    "grammatical particle": PART,
    "infinitive marker": PART,
    "acronym": OTHER,
}
